// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetResponse {
    #[prost(message, optional, tag = "1")]
    pub address: ::core::option::Option<crate::lore::model::v1::Address>,
    #[prost(message, optional, tag = "2")]
    pub fragment: ::core::option::Option<crate::lore::model::v1::Fragment>,
    #[prost(bytes = "bytes", tag = "3")]
    pub payload: ::prost::bytes::Bytes,
}
impl ::prost::Name for GetResponse {
    const NAME: &'static str = "GetResponse";
    const PACKAGE: &'static str = "lore.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.storage.v1.GetResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.storage.v1.GetResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UploadContentRequest {
    #[prost(oneof = "upload_content_request::Part", tags = "1, 2")]
    pub part: ::core::option::Option<upload_content_request::Part>,
}
/// Nested message and enum types in `UploadContentRequest`.
pub mod upload_content_request {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Part {
        /// Required exactly once as the first stream message.
        #[prost(message, tag = "1")]
        Header(super::UploadContentHeader),
        /// Raw file bytes. Chunks may be any non-empty transport-friendly size;
        /// callers must not pre-fragment them according to Lore internals.
        #[prost(bytes, tag = "2")]
        Chunk(::prost::bytes::Bytes),
    }
}
impl ::prost::Name for UploadContentRequest {
    const NAME: &'static str = "UploadContentRequest";
    const PACKAGE: &'static str = "lore.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.storage.v1.UploadContentRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.storage.v1.UploadContentRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UploadContentHeader {
    /// UUIDv7 file identity. Use the existing address context when modifying a
    /// file. Empty asks Lore to mint a UUIDv7 for a new file.
    #[prost(bytes = "bytes", tag = "1")]
    pub file_id: ::prost::bytes::Bytes,
    /// Optional integrity assertion checked against the actual bytes read.
    #[prost(uint64, optional, tag = "2")]
    pub expected_size: ::core::option::Option<u64>,
    /// Required caller-generated UUIDv7 for retry/correlation diagnostics.
    #[prost(bytes = "bytes", tag = "3")]
    pub request_id: ::prost::bytes::Bytes,
}
impl ::prost::Name for UploadContentHeader {
    const NAME: &'static str = "UploadContentHeader";
    const PACKAGE: &'static str = "lore.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.storage.v1.UploadContentHeader".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.storage.v1.UploadContentHeader".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UploadContentResponse {
    #[prost(message, optional, tag = "1")]
    pub address: ::core::option::Option<crate::lore::model::v1::Address>,
    /// Actual logical byte count observed by Lore.
    #[prost(uint64, tag = "2")]
    pub size: u64,
}
impl ::prost::Name for UploadContentResponse {
    const NAME: &'static str = "UploadContentResponse";
    const PACKAGE: &'static str = "lore.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.storage.v1.UploadContentResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.storage.v1.UploadContentResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PutRequest {
    #[prost(message, optional, tag = "1")]
    pub address: ::core::option::Option<crate::lore::model::v1::Address>,
    #[prost(message, optional, tag = "2")]
    pub fragment: ::core::option::Option<crate::lore::model::v1::Fragment>,
    #[prost(bytes = "bytes", optional, tag = "3")]
    pub payload: ::core::option::Option<::prost::bytes::Bytes>,
}
impl ::prost::Name for PutRequest {
    const NAME: &'static str = "PutRequest";
    const PACKAGE: &'static str = "lore.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.storage.v1.PutRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.storage.v1.PutRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PutResponse {
    #[prost(message, optional, tag = "1")]
    pub address: ::core::option::Option<crate::lore::model::v1::Address>,
}
impl ::prost::Name for PutResponse {
    const NAME: &'static str = "PutResponse";
    const PACKAGE: &'static str = "lore.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.storage.v1.PutResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.storage.v1.PutResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryRequest {
    #[prost(message, repeated, tag = "1")]
    pub addresses: ::prost::alloc::vec::Vec<crate::lore::model::v1::Address>,
}
impl ::prost::Name for QueryRequest {
    const NAME: &'static str = "QueryRequest";
    const PACKAGE: &'static str = "lore.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.storage.v1.QueryRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.storage.v1.QueryRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryResponse {
    #[prost(enumeration = "crate::lore::model::v1::FragmentState", repeated, tag = "1")]
    pub results: ::prost::alloc::vec::Vec<i32>,
}
impl ::prost::Name for QueryResponse {
    const NAME: &'static str = "QueryResponse";
    const PACKAGE: &'static str = "lore.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.storage.v1.QueryResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.storage.v1.QueryResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PresignDownloadRequest {
    #[prost(message, repeated, tag = "1")]
    pub addresses: ::prost::alloc::vec::Vec<crate::lore::model::v1::Address>,
    #[prost(uint64, tag = "2")]
    pub expires_in_seconds: u64,
}
impl ::prost::Name for PresignDownloadRequest {
    const NAME: &'static str = "PresignDownloadRequest";
    const PACKAGE: &'static str = "lore.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.storage.v1.PresignDownloadRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.storage.v1.PresignDownloadRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PresignedDownload {
    #[prost(message, optional, tag = "1")]
    pub address: ::core::option::Option<crate::lore::model::v1::Address>,
    #[prost(message, optional, tag = "2")]
    pub fragment: ::core::option::Option<crate::lore::model::v1::Fragment>,
    #[prost(string, tag = "3")]
    pub url: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub expires_at_epoch_seconds: u64,
}
impl ::prost::Name for PresignedDownload {
    const NAME: &'static str = "PresignedDownload";
    const PACKAGE: &'static str = "lore.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.storage.v1.PresignedDownload".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.storage.v1.PresignedDownload".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PresignDownloadResponse {
    #[prost(message, repeated, tag = "1")]
    pub downloads: ::prost::alloc::vec::Vec<PresignedDownload>,
}
impl ::prost::Name for PresignDownloadResponse {
    const NAME: &'static str = "PresignDownloadResponse";
    const PACKAGE: &'static str = "lore.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.storage.v1.PresignDownloadResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.storage.v1.PresignDownloadResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyRequest {
    #[prost(message, optional, tag = "1")]
    pub address: ::core::option::Option<crate::lore::model::v1::Address>,
    #[prost(bool, tag = "2")]
    pub heal: bool,
}
impl ::prost::Name for VerifyRequest {
    const NAME: &'static str = "VerifyRequest";
    const PACKAGE: &'static str = "lore.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.storage.v1.VerifyRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.storage.v1.VerifyRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyResponse {
    #[prost(enumeration = "HealResult", tag = "1")]
    pub healed: i32,
    #[prost(bool, tag = "2")]
    pub corrupted: bool,
}
impl ::prost::Name for VerifyResponse {
    const NAME: &'static str = "VerifyResponse";
    const PACKAGE: &'static str = "lore.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.storage.v1.VerifyResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.storage.v1.VerifyResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CopyRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub source_repository_id: ::prost::bytes::Bytes,
    #[prost(message, optional, tag = "2")]
    pub source_address: ::core::option::Option<crate::lore::model::v1::Address>,
    /// Destination context. The destination address is
    /// (target_repository, source_address.hash, target_context). When omitted (zero bytes), the
    /// server treats the destination context as the source's, preserving legacy semantics.
    #[prost(bytes = "bytes", tag = "3")]
    pub target_context: ::prost::bytes::Bytes,
}
impl ::prost::Name for CopyRequest {
    const NAME: &'static str = "CopyRequest";
    const PACKAGE: &'static str = "lore.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.storage.v1.CopyRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.storage.v1.CopyRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CopyResponse {
    #[prost(bytes = "bytes", tag = "1")]
    pub source_repository_id: ::prost::bytes::Bytes,
    #[prost(message, optional, tag = "2")]
    pub source_address: ::core::option::Option<crate::lore::model::v1::Address>,
}
impl ::prost::Name for CopyResponse {
    const NAME: &'static str = "CopyResponse";
    const PACKAGE: &'static str = "lore.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.storage.v1.CopyResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.storage.v1.CopyResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MutableLoadRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub key: ::prost::bytes::Bytes,
    #[prost(uint32, tag = "2")]
    pub key_type: u32,
}
impl ::prost::Name for MutableLoadRequest {
    const NAME: &'static str = "MutableLoadRequest";
    const PACKAGE: &'static str = "lore.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.storage.v1.MutableLoadRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.storage.v1.MutableLoadRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MutableLoadResponse {
    #[prost(bytes = "bytes", tag = "1")]
    pub value: ::prost::bytes::Bytes,
}
impl ::prost::Name for MutableLoadResponse {
    const NAME: &'static str = "MutableLoadResponse";
    const PACKAGE: &'static str = "lore.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.storage.v1.MutableLoadResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.storage.v1.MutableLoadResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MutableStoreRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub key: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "2")]
    pub value: ::prost::bytes::Bytes,
    #[prost(uint32, tag = "3")]
    pub key_type: u32,
}
impl ::prost::Name for MutableStoreRequest {
    const NAME: &'static str = "MutableStoreRequest";
    const PACKAGE: &'static str = "lore.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.storage.v1.MutableStoreRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.storage.v1.MutableStoreRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MutableStoreResponse {}
impl ::prost::Name for MutableStoreResponse {
    const NAME: &'static str = "MutableStoreResponse";
    const PACKAGE: &'static str = "lore.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.storage.v1.MutableStoreResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.storage.v1.MutableStoreResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MutableCompareAndSwapRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub key: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "2")]
    pub expected: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "3")]
    pub value: ::prost::bytes::Bytes,
    #[prost(uint32, tag = "4")]
    pub key_type: u32,
}
impl ::prost::Name for MutableCompareAndSwapRequest {
    const NAME: &'static str = "MutableCompareAndSwapRequest";
    const PACKAGE: &'static str = "lore.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.storage.v1.MutableCompareAndSwapRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.storage.v1.MutableCompareAndSwapRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MutableCompareAndSwapResponse {
    #[prost(bytes = "bytes", tag = "1")]
    pub current_value: ::prost::bytes::Bytes,
}
impl ::prost::Name for MutableCompareAndSwapResponse {
    const NAME: &'static str = "MutableCompareAndSwapResponse";
    const PACKAGE: &'static str = "lore.storage.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.storage.v1.MutableCompareAndSwapResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.storage.v1.MutableCompareAndSwapResponse".into()
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum HealResult {
    NotAttempted = 0,
    Success = 1,
    Failed = 2,
}
impl HealResult {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::NotAttempted => "NOT_ATTEMPTED",
            Self::Success => "SUCCESS",
            Self::Failed => "FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NOT_ATTEMPTED" => Some(Self::NotAttempted),
            "SUCCESS" => Some(Self::Success),
            "FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod storage_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct StorageServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl StorageServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> StorageServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> StorageServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            StorageServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn get(
            &mut self,
            request: impl tonic::IntoStreamingRequest<
                Message = crate::lore::model::v1::Address,
            >,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::GetResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.storage.v1.StorageService/Get",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("lore.storage.v1.StorageService", "Get"));
            self.inner.streaming(req, path, codec).await
        }
        /// GetMetadata: same wire request as Get (just an Address), but the server's response
        /// carries Fragment only — no payload bytes. Used by callers that need fragment metadata
        /// (size, flags) for existence/size lookups without paying the payload transfer cost.
        pub async fn get_metadata(
            &mut self,
            request: impl tonic::IntoStreamingRequest<
                Message = crate::lore::model::v1::Address,
            >,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::GetResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.storage.v1.StorageService/GetMetadata",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("lore.storage.v1.StorageService", "GetMetadata"),
                );
            self.inner.streaming(req, path, codec).await
        }
        /// UploadContent accepts one header followed by raw byte chunks. Lore owns
        /// chunking, hashing, compression, fragment-list construction, and durable
        /// storage. Cancellation can leave unreachable content-addressed fragments;
        /// it never publishes a revision or branch.
        pub async fn upload_content(
            &mut self,
            request: impl tonic::IntoStreamingRequest<
                Message = super::UploadContentRequest,
            >,
        ) -> std::result::Result<
            tonic::Response<super::UploadContentResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.storage.v1.StorageService/UploadContent",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("lore.storage.v1.StorageService", "UploadContent"),
                );
            self.inner.client_streaming(req, path, codec).await
        }
        pub async fn put(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::PutRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::PutResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.storage.v1.StorageService/Put",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("lore.storage.v1.StorageService", "Put"));
            self.inner.streaming(req, path, codec).await
        }
        pub async fn query(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryRequest>,
        ) -> std::result::Result<tonic::Response<super::QueryResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.storage.v1.StorageService/Query",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("lore.storage.v1.StorageService", "Query"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn presign_download(
            &mut self,
            request: impl tonic::IntoRequest<super::PresignDownloadRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PresignDownloadResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.storage.v1.StorageService/PresignDownload",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("lore.storage.v1.StorageService", "PresignDownload"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn verify(
            &mut self,
            request: impl tonic::IntoRequest<super::VerifyRequest>,
        ) -> std::result::Result<tonic::Response<super::VerifyResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.storage.v1.StorageService/Verify",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("lore.storage.v1.StorageService", "Verify"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn copy(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::CopyRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::CopyResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.storage.v1.StorageService/Copy",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("lore.storage.v1.StorageService", "Copy"));
            self.inner.streaming(req, path, codec).await
        }
        pub async fn mutable_load(
            &mut self,
            request: impl tonic::IntoRequest<super::MutableLoadRequest>,
        ) -> std::result::Result<
            tonic::Response<super::MutableLoadResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.storage.v1.StorageService/MutableLoad",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("lore.storage.v1.StorageService", "MutableLoad"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn mutable_store(
            &mut self,
            request: impl tonic::IntoRequest<super::MutableStoreRequest>,
        ) -> std::result::Result<
            tonic::Response<super::MutableStoreResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.storage.v1.StorageService/MutableStore",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("lore.storage.v1.StorageService", "MutableStore"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn mutable_compare_and_swap(
            &mut self,
            request: impl tonic::IntoRequest<super::MutableCompareAndSwapRequest>,
        ) -> std::result::Result<
            tonic::Response<super::MutableCompareAndSwapResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.storage.v1.StorageService/MutableCompareAndSwap",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "lore.storage.v1.StorageService",
                        "MutableCompareAndSwap",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod storage_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with StorageServiceServer.
    #[async_trait]
    pub trait StorageService: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the Get method.
        type GetStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::GetResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn get(
            &self,
            request: tonic::Request<tonic::Streaming<crate::lore::model::v1::Address>>,
        ) -> std::result::Result<tonic::Response<Self::GetStream>, tonic::Status>;
        /// Server streaming response type for the GetMetadata method.
        type GetMetadataStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::GetResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// GetMetadata: same wire request as Get (just an Address), but the server's response
        /// carries Fragment only — no payload bytes. Used by callers that need fragment metadata
        /// (size, flags) for existence/size lookups without paying the payload transfer cost.
        async fn get_metadata(
            &self,
            request: tonic::Request<tonic::Streaming<crate::lore::model::v1::Address>>,
        ) -> std::result::Result<
            tonic::Response<Self::GetMetadataStream>,
            tonic::Status,
        >;
        /// UploadContent accepts one header followed by raw byte chunks. Lore owns
        /// chunking, hashing, compression, fragment-list construction, and durable
        /// storage. Cancellation can leave unreachable content-addressed fragments;
        /// it never publishes a revision or branch.
        async fn upload_content(
            &self,
            request: tonic::Request<tonic::Streaming<super::UploadContentRequest>>,
        ) -> std::result::Result<
            tonic::Response<super::UploadContentResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the Put method.
        type PutStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::PutResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn put(
            &self,
            request: tonic::Request<tonic::Streaming<super::PutRequest>>,
        ) -> std::result::Result<tonic::Response<Self::PutStream>, tonic::Status>;
        async fn query(
            &self,
            request: tonic::Request<super::QueryRequest>,
        ) -> std::result::Result<tonic::Response<super::QueryResponse>, tonic::Status>;
        async fn presign_download(
            &self,
            request: tonic::Request<super::PresignDownloadRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PresignDownloadResponse>,
            tonic::Status,
        >;
        async fn verify(
            &self,
            request: tonic::Request<super::VerifyRequest>,
        ) -> std::result::Result<tonic::Response<super::VerifyResponse>, tonic::Status>;
        /// Server streaming response type for the Copy method.
        type CopyStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::CopyResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn copy(
            &self,
            request: tonic::Request<tonic::Streaming<super::CopyRequest>>,
        ) -> std::result::Result<tonic::Response<Self::CopyStream>, tonic::Status>;
        async fn mutable_load(
            &self,
            request: tonic::Request<super::MutableLoadRequest>,
        ) -> std::result::Result<
            tonic::Response<super::MutableLoadResponse>,
            tonic::Status,
        >;
        async fn mutable_store(
            &self,
            request: tonic::Request<super::MutableStoreRequest>,
        ) -> std::result::Result<
            tonic::Response<super::MutableStoreResponse>,
            tonic::Status,
        >;
        async fn mutable_compare_and_swap(
            &self,
            request: tonic::Request<super::MutableCompareAndSwapRequest>,
        ) -> std::result::Result<
            tonic::Response<super::MutableCompareAndSwapResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct StorageServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> StorageServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for StorageServiceServer<T>
    where
        T: StorageService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/lore.storage.v1.StorageService/Get" => {
                    #[allow(non_camel_case_types)]
                    struct GetSvc<T: StorageService>(pub Arc<T>);
                    impl<
                        T: StorageService,
                    > tonic::server::StreamingService<crate::lore::model::v1::Address>
                    for GetSvc<T> {
                        type Response = super::GetResponse;
                        type ResponseStream = T::GetStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<crate::lore::model::v1::Address>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StorageService>::get(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.storage.v1.StorageService/GetMetadata" => {
                    #[allow(non_camel_case_types)]
                    struct GetMetadataSvc<T: StorageService>(pub Arc<T>);
                    impl<
                        T: StorageService,
                    > tonic::server::StreamingService<crate::lore::model::v1::Address>
                    for GetMetadataSvc<T> {
                        type Response = super::GetResponse;
                        type ResponseStream = T::GetMetadataStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<crate::lore::model::v1::Address>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StorageService>::get_metadata(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetMetadataSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.storage.v1.StorageService/UploadContent" => {
                    #[allow(non_camel_case_types)]
                    struct UploadContentSvc<T: StorageService>(pub Arc<T>);
                    impl<
                        T: StorageService,
                    > tonic::server::ClientStreamingService<super::UploadContentRequest>
                    for UploadContentSvc<T> {
                        type Response = super::UploadContentResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::UploadContentRequest>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StorageService>::upload_content(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UploadContentSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.client_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.storage.v1.StorageService/Put" => {
                    #[allow(non_camel_case_types)]
                    struct PutSvc<T: StorageService>(pub Arc<T>);
                    impl<
                        T: StorageService,
                    > tonic::server::StreamingService<super::PutRequest> for PutSvc<T> {
                        type Response = super::PutResponse;
                        type ResponseStream = T::PutStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<tonic::Streaming<super::PutRequest>>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StorageService>::put(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PutSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.storage.v1.StorageService/Query" => {
                    #[allow(non_camel_case_types)]
                    struct QuerySvc<T: StorageService>(pub Arc<T>);
                    impl<
                        T: StorageService,
                    > tonic::server::UnaryService<super::QueryRequest> for QuerySvc<T> {
                        type Response = super::QueryResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::QueryRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StorageService>::query(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = QuerySvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.storage.v1.StorageService/PresignDownload" => {
                    #[allow(non_camel_case_types)]
                    struct PresignDownloadSvc<T: StorageService>(pub Arc<T>);
                    impl<
                        T: StorageService,
                    > tonic::server::UnaryService<super::PresignDownloadRequest>
                    for PresignDownloadSvc<T> {
                        type Response = super::PresignDownloadResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PresignDownloadRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StorageService>::presign_download(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PresignDownloadSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.storage.v1.StorageService/Verify" => {
                    #[allow(non_camel_case_types)]
                    struct VerifySvc<T: StorageService>(pub Arc<T>);
                    impl<
                        T: StorageService,
                    > tonic::server::UnaryService<super::VerifyRequest>
                    for VerifySvc<T> {
                        type Response = super::VerifyResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::VerifyRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StorageService>::verify(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = VerifySvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.storage.v1.StorageService/Copy" => {
                    #[allow(non_camel_case_types)]
                    struct CopySvc<T: StorageService>(pub Arc<T>);
                    impl<
                        T: StorageService,
                    > tonic::server::StreamingService<super::CopyRequest>
                    for CopySvc<T> {
                        type Response = super::CopyResponse;
                        type ResponseStream = T::CopyStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<tonic::Streaming<super::CopyRequest>>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StorageService>::copy(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CopySvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.storage.v1.StorageService/MutableLoad" => {
                    #[allow(non_camel_case_types)]
                    struct MutableLoadSvc<T: StorageService>(pub Arc<T>);
                    impl<
                        T: StorageService,
                    > tonic::server::UnaryService<super::MutableLoadRequest>
                    for MutableLoadSvc<T> {
                        type Response = super::MutableLoadResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MutableLoadRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StorageService>::mutable_load(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = MutableLoadSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.storage.v1.StorageService/MutableStore" => {
                    #[allow(non_camel_case_types)]
                    struct MutableStoreSvc<T: StorageService>(pub Arc<T>);
                    impl<
                        T: StorageService,
                    > tonic::server::UnaryService<super::MutableStoreRequest>
                    for MutableStoreSvc<T> {
                        type Response = super::MutableStoreResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MutableStoreRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StorageService>::mutable_store(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = MutableStoreSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.storage.v1.StorageService/MutableCompareAndSwap" => {
                    #[allow(non_camel_case_types)]
                    struct MutableCompareAndSwapSvc<T: StorageService>(pub Arc<T>);
                    impl<
                        T: StorageService,
                    > tonic::server::UnaryService<super::MutableCompareAndSwapRequest>
                    for MutableCompareAndSwapSvc<T> {
                        type Response = super::MutableCompareAndSwapResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MutableCompareAndSwapRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StorageService>::mutable_compare_and_swap(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = MutableCompareAndSwapSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for StorageServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "lore.storage.v1.StorageService";
    impl<T> tonic::server::NamedService for StorageServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
